# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.5
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: 132695189+sparky0520@users.noreply.github.com
author_name: Darsh Jain
contract_name: hello_world
preset_name: starter
project_name: algorand_test

